name: Documentation

on:
  push:
    branches: [ main ]
    # Always run on commits

  pull_request:
    paths:
        - 'linera-protocol'
        - 'src/**'
        - 'book.toml'
        - '.github/workflows/documentation.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: 'Setup mdbook'
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: 'Build the Linera SDK'
        run: |
          cd linera-protocol
          cargo build --locked -p linera-sdk --features test,wasmer

      - name: 'Check documentation'
        run: mdbook test -L linera-protocol/target/debug/deps/

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 'Install prettier'
        run: npm install -g prettier

      - name: 'Check formatting'
        run: prettier --check src/
